#!/usr/bin/env bun
import { answerSignals } from "../answer.ts";
import { ensureDependenciesInstalled } from "../bootstrap.ts";

ensureDependenciesInstalled();
answerSignals();
const { main } = await import("./cli.ts");
process.exitCode = await main(process.argv.slice(2));
